// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * PokéAPI
 * The RESTful Pokémon API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AbilityGeneration
 */
export interface AbilityGeneration {
    /**
     * 
     * @type {string}
     * @memberof AbilityGeneration
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AbilityGeneration
     */
    url?: string;
}


