// tslint:disable
/**
 * PokéAPI
 * The RESTful Pokémon API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AbilityGeneration } from './ability-generation';

/**
 * 
 * @export
 * @interface Ability
 */
export interface Ability {
    /**
     * 
     * @type {number}
     * @memberof Ability
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Ability
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof Ability
     */
    isMainSeries?: boolean;
    /**
     * 
     * @type {AbilityGeneration}
     * @memberof Ability
     */
    generation: AbilityGeneration;
    /**
     * 
     * @type {Array<object>}
     * @memberof Ability
     */
    names?: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof Ability
     */
    effectEntries?: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof Ability
     */
    effectChanges?: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof Ability
     */
    flavorTextEntries?: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof Ability
     */
    pokemon?: string;
}


