// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * PokéAPI
 * The RESTful Pokémon API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BerryFirmness
 */
export interface BerryFirmness {
    /**
     * 
     * @type {number}
     * @memberof BerryFirmness
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof BerryFirmness
     */
    name: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof BerryFirmness
     */
    berries?: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof BerryFirmness
     */
    names?: Array<object>;
}


