// tslint:disable
/**
 * PokéAPI
 * The RESTful Pokémon API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AbilityGeneration } from './ability-generation';

/**
 * 
 * @export
 * @interface Berry
 */
export interface Berry {
    /**
     * 
     * @type {number}
     * @memberof Berry
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Berry
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Berry
     */
    growthTime: number;
    /**
     * 
     * @type {number}
     * @memberof Berry
     */
    maxHarvest: number;
    /**
     * 
     * @type {number}
     * @memberof Berry
     */
    naturalGiftPower: number;
    /**
     * 
     * @type {number}
     * @memberof Berry
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof Berry
     */
    smoothness: number;
    /**
     * 
     * @type {number}
     * @memberof Berry
     */
    soilDryness: number;
    /**
     * 
     * @type {AbilityGeneration}
     * @memberof Berry
     */
    firmness: AbilityGeneration;
    /**
     * 
     * @type {string}
     * @memberof Berry
     */
    flavors?: string;
    /**
     * 
     * @type {AbilityGeneration}
     * @memberof Berry
     */
    item: AbilityGeneration;
    /**
     * 
     * @type {AbilityGeneration}
     * @memberof Berry
     */
    naturalGiftType: AbilityGeneration;
}


