// tslint:disable
/**
 * PokéAPI
 * The RESTful Pokémon API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NamedAPIResourceList
 */
export interface NamedAPIResourceList {
    /**
     * 
     * @type {number}
     * @memberof NamedAPIResourceList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof NamedAPIResourceList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NamedAPIResourceList
     */
    previous?: string | null;
}


