// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * PokéAPI
 * The RESTful Pokémon API
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AbilityGeneration } from './ability-generation';

/**
 * 
 * @export
 * @interface Pokemon
 */
export interface Pokemon {
    /**
     * 
     * @type {number}
     * @memberof Pokemon
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Pokemon
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Pokemon
     */
    baseExperience: number;
    /**
     * 
     * @type {number}
     * @memberof Pokemon
     */
    height: number;
    /**
     * 
     * @type {boolean}
     * @memberof Pokemon
     */
    isDefault?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Pokemon
     */
    order?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Pokemon
     */
    weight: number;
    /**
     * 
     * @type {string}
     * @memberof Pokemon
     */
    abilities?: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof Pokemon
     */
    forms?: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof Pokemon
     */
    gameIndices?: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof Pokemon
     */
    heldItems?: string;
    /**
     * 
     * @type {string}
     * @memberof Pokemon
     */
    locationAreaEncounters?: string;
    /**
     * 
     * @type {string}
     * @memberof Pokemon
     */
    moves?: string;
    /**
     * 
     * @type {AbilityGeneration}
     * @memberof Pokemon
     */
    species: AbilityGeneration;
    /**
     * 
     * @type {string}
     * @memberof Pokemon
     */
    sprites?: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof Pokemon
     */
    stats?: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof Pokemon
     */
    types?: string;
}


